### ISSUE TITLE
Add a parameter to artificial_ssl_dataset to force a number of minimum samples per class in labeled data

### ISSUE THREAD

**Issue by Josemi** [jlgarridol/sslearn#11]

**Comment by jlgarridol** [comment]
Thanks, feature added. Keep waiting for the next release.

**Comment by Josemi** [comment]
![image](https://github.com/jlgarridol/sslearn/assets/22240279/a5261981-78e5-4de9-80ed-b65945e3a081)
Where is the release?

**Comment by Josemi** [comment]
![v9kj1mfe749b1](https://github.com/jlgarridol/sslearn/assets/22240279/46b29421-34fc-4e3e-8bd0-caabef227df7)
Where is the release?

**Comment by jlgarridol** [comment]
In a month
